# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: /tmp/portal-project 
  docker:
    - image: circleci/node:8
  
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install Deps
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Build Project
          command: yarn run build
      - persist_to_workspace: 
          root: /tmp
          paths:
            - portal-project
  deploy_to_prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/portal-project
      - run: yarn add firebase-tools
      - run: ./node_modules/.bin/firebase use prod
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting
  deploy_to_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/portal-project
      - run: yarn add firebase-tools
      - run: ./node_modules/.bin/firebase use dev
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
      - deploy_to_prod:
          requires: 
            - build
          filters:
            branches:
              only:
                - master
      - deploy_to_dev:
          requires:
            - build
          filters:
            branches:
              only:
                - dev