# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/portal-project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run build
      - run: yarn add firebase-tools
      - deploy:
          name: Deploy Master to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pushd . && cd functions/
              yarn
              popd
              ./node_modules/.bin/firebase use prod
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
            fi
      - deploy:
          name: Deploy Dev to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              ./node_modules/.bin/firebase use dev
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
            fi